### ISSUE TITLE
3.0 idea

### ISSUE THREAD

**Issue by medz** [medz/spry#78]
After practicing in many projects, we found many shortcomings of Spry.

I'm planning an optimization for version 3.0 and am eager to hear everyone's suggestions for changes.

**Comment by SirusCodes** [comment]
Can you elaborate what do you think are shortcoming of spry?

**Comment by medz** [comment]
@SirusCodes 1. The handler is not very friendly for Function
2. The handler is called one more layer through the context, req/res is actually the most commonly used
3. Next calls without side effects can lead to the need for non-standard middleware or unpredictable execution order.
4. No chain predictability
5. The routes function is most commonly used and expected to be integrated.
6. The response in a request cycle is a single object, which is not conducive to process prediction.

My initial thoughts:

- Look for the standard Request object, with easy-to-use wrappers
- Make a response returned by the handler similar to shelf
- Integrate router functionality into app.

**Comment by medz** [comment]
A development preview has been released https://pub.dev/packages/spry/versions/3.0.0-dev.2/example
